### ISSUE TITLE
I've met this error when ipynb run.

### ISSUE THREAD

**Issue by bemoregt** [zedge/GANforiPhoneWithCoreML#2]
Hi, @ThomasPedersen @toxic @retallicka @stigsb @atveit 

I've met this error when ipynb run.

"Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)"

What's wrong to me?

from @bemoregt.

**Comment by stigsb** [comment]
@bemoregt looks like a transient problem, either because your local certificates are out of date, or because your network connection hits some kind of proxy. If you can open the link in your browser, but not in Python, then you should try doing a software update.
Closing since this is a local issue.
